language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
script: npm test
notifications:
  irc:
    channels:
      - "irc.w3.org#social"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
